language: objective-c

osx_image: xcode8.1

branches:
  only:
    - master

before_install:
  - bundle
  - pod install --project-directory=Tests

env:
  global:
    - WORKSPACE="Tests/Tests.xcworkspace"
    - SCHEME="Tests"
    - DESTINATION="Tests"
    - SDK="iphonesimulator10.1"
    - DESTINATION="name=iPhone 6,OS=10.1"

script:
  - set -o pipefail
  - xcodebuild build-for-testing test-without-building -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES | xcpretty -c
