@import Foundation;

@class BTNBoostView, BTNPurchasePathRequest;

NS_ASSUME_NONNULL_BEGIN

NS_SWIFT_NAME(BoostViewDelegate)
@protocol BTNBoostViewDelegate <NSObject>

/**
 Invoked when a user interacts with a BoostView.
 
 @discussion Implement this delegate if you intend to show brand terms or
 details before a PurchasePath is started. By default, the Button SDK will
 automatically fetch and start PurchasePaths generated by a BoostView.
 
 @code
 // Fetch & start the purchasePathRequest once you've displayed your UI to your user.
 [Button.purchasePath fetchWithRequest:purchasePathRequest
                   purchasePathHandler:^(BTNPurchasePath *purchasePath, NSError *error) {
     if (purchasePath) {
         [purchasePath start];
     }
 }];
 @endcode
 
 @param boostView The Boost view that, through user interaction, triggered the request.
 @param purchasePathRequest The request to be executed to obtain a PurchasePath object.
 @param organizationId The identifier of the merchant organization for the PurchasePath.
 */
- (void)boostView:(BTNBoostView *)boostView
didReceiveRequest:(BTNPurchasePathRequest *)purchasePathRequest
   organizationId:(NSString *)organizationId;

@end

NS_ASSUME_NONNULL_END
