source 'git@github.com:button/podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

pod 'Button', '6.26.0'
pod 'Sourcery'

target 'Swift-Demo' do
  use_frameworks!
end

target 'ObjC-Demo' do
end
